### ISSUE TITLE
[개발] Learning React

### ISSUE THREAD

**Issue by dltkddns833** [dltkddns833/YHMG#5]
## TODO
- [ ] (2D)NomadCoder 완강
- [ ] (2D)클론코딩(사이트 미정)
## NEXT
- [ ] (5D)책 완주
## DONE
- [x] (0.5D)React 공부 => 웹 프레임워크의 개념에 대해서 알아보기
- [x] (0.5D)React가 어떤 것인지 인지할 것

**Comment by joonyy** [comment]
https://www.notion.so/d99e8f99edb643ada75450dc42f8ef92?v=7ae0d66b2e884b6cb98b0334571d05d8&p=160be00d596c4af3ba8c65730e3d1671&pm=s
